### ISSUE TITLE
Login/Sign up 

### ISSUE THREAD

**Issue by msabukwaik** [mocashapp/laravel-app#24]
As a user I want to be able to sign in/up from the mobile so that I can have my own account

Acceptance criteria : 
- Run the application
- The login screen should be appeared immediately after the splash screen 
- The user should enter his mobile account, and then clicks over the login button 
- Once the user clicks over the login button, sms should be sent to the customer with an activation message, and the user should be redirected to the activation screen
- Once the user enter the activation number, the user system should check it in case every thing is going well then the user should be redirected to the set profile screen
- In the set profile screen, the user should be able to set his information "full name, image, pin" 
- Once the user fill the information the system should redirect him to the dashboard screen

**Comment by wshurafa** [comment]
Backed done:
https://github.com/mocashapp/laravel-app/pull/38
