### ISSUE TITLE
Server side - pay service

### ISSUE THREAD

**Issue by msabukwaik** [mocashapp/laravel-app#4]
Please create a service that pay the requested amount to the requester user. The information related to the service are listed below

Input : 
- The ID of the receiver 
- The full name of the receiver
- The amount of the receiver
- The details of the requesting
- The pass/pin of the sender

It returns
- status : true/false
- balance after being effected.

**Comment by mzaalan** [comment]
https://github.com/mocashapp/laravel-app/pull/29
